### ISSUE TITLE
TODO for lib/opts

### ISSUE THREAD

**Issue by privat** [privat/nit#1273]
* [ ] possiblitity to detect bad options (instead of feeding them as arguments)
* [ ] groups (category) of options to orderize and title related options 
* [ ] suggestion in case of bad option
* [ ] process alternative value parsing (like `-ovalue` and `--option=value`)
* [ ] see if an option is still at the default value or if it was set
* [ ] automatic negation of boolean (like `--no-something` for `--something`)
