### ISSUE TITLE
nitiwiki todo list

### ISSUE THREAD

**Issue by privat** [privat/nit#1507]
Now that a beta of the new website is available http://nitlanguage.org/beta what is missing?

To become official

* [ ] global table of content (with trails) so people can navigate in the manual
* [ ] nitlighting to highlight code
* [ ] standard documented procedure for github-hooks that regen the site
* [ ] tables? http://nitlanguage.org/beta/FFI/

Other nice things to have

* [ ] other highlighting (with a 3rd-party tool)
* [ ] check dead external links
