### ISSUE TITLE
Use our own medecine

### ISSUE THREAD

**Issue by privat** [privat/nit#824]
* [x] nitcorn: done with nitrpg (#1142)
 * [x] nitiwiki: incomming with nitlanguage.org (#1444)
 * [ ] md->man conversion (instead of pandoc) (#1506)
